def new_employee_dictionary():
    return {
        "SSF Contribution by Employer": "", # Just to make its next column value evaluated
        "Employee ID": "",
        "Employee Name": "",
        "Designation": "",
        "PAN": "",
        "Contact Number": "",
        "Basic Salary": "",
        "Allowances": "",
        "Gross Salary": "",
        "Gross Salary as per working hours": "",
        "Upper SSF Contribution by Employer": "",
        "Lower SSF Contribution by Employer": "",
        "Bonus": "",
        "Total": "",
        "SSF Contribution by Employee": "", 
        "TDS for the month": "", 
        "Total Deduction": "", 
        "Net Salary Paid": "", 
        "Account Number": "", 
        "Bank Name": "",
        "Branch": "",
        "Marital Status": "",
        "Annual Taxable Salary": "",
        "Annual SSF deposit": "",
        "Annual TDS Payment": "",
        "Annual Net Salary": "",
        "Month": "",
        "Financial_Year_Note": "", 
        "Month_year": ""
}